### ISSUE TITLE
Shelly Button1 _ CoAP _ "inputEvent" and "inputEventCnt" Entities are not created

### ISSUE THREAD

**Issue by runwaygoats** [home-assistant-libs/aioshelly#108]
Not sure if this is the right place or way to report this.

When I added Shelly Button1 to Home Assistant through native integration, only remaining battery percentage entity is created.

inputEvent and inputEventCnt are not created.

I have deleted and added many times, just to be sure.

As a workaround, I have added it manually through MQTT and it is working fine.

I have the following Shelly devices, that I also added through native integration. No problem with them:

Door/Window2
Shelly Humidity and Temperature Sensor
BulbDuo
Switch2.5

# System Details
Home Assistant 2021.6.0

Shelly Button1
Firmware 20210415-130655/v1.10.3-g23074d0 

http://......./cit/d

{"blk":[{"I":1,"D":"sensor_0"},{"I":2,"D":"device"}],"sen":[{"I":9103,"T":"EVC","D":"cfgChanged","R":"U16","L":2},{"I":2102,"T":"EV","D":"inputEvent","R":["S/L/SS/SSS",""],"L":1},{"I":2103,"T":"EVC","D":"inputEventCnt","R":"U16","L":1},{"I":3115,"T":"S","D":"sensorError","R":"0/1","L":1},{"I":3112,"T":"S","D":"charger","R":["0/1","-1"],"L":2},{"I":3111,"T":"B","D":"battery","R":["0/100","-1"],"L":2},{"I":9102,"T":"EV","D":"wakeupEvent","R":["battery/button/periodic/poweron/sensor/ext_power","unknown"],"L":2}]}

**Comment by bieniu** [comment]
Your issue is related to HA integration so it should be opened here https://github.com/home-assistant/core/issues

Input events from the device are handled in the Home Assistant as events https://www.home-assistant.io/integrations/shelly/#events
