### ISSUE TITLE
aioshelly mcast ignores network interfaces settings

### ISSUE THREAD

**Issue by buzz-tee** [home-assistant-libs/aioshelly#149]
With the current implementation the multicast group membership will always be added to the interface that holds the default route. In my case this is wrong, since my system is multi-homed with default route pointing to eth0 and my Shelly's will communicate via eth1. As a result CoIoT notifications won't work and HA will fall back to polling.

See below the IGMP memberships on my system, with group BB0100E0 (which translates to 224.0.1.187) configured on eth0 when it should be on eth1:
```bash
bash-5.1# cat /proc/net/igmp
Idx	Device    : Count Querier	Group    Users Timer	Reporter
1	lo        :     1      V3
				010000E0     1 0:00000000		0
380	eth0      :     2      V3
				BB0100E0     1 0:00000000		0
				010000E0     1 0:00000000		0
378	eth1      :     3      V3
				FAFFFFEF     2 0:00000000		0
				FB0000E0     1 0:00000000		0
				010000E0     1 0:00000000		0
379	eth2      :     1      V3
				010000E0     1 0:00000000		0
```

The source code suggests the group membership should be configured on all interfaces (since IP_ADD_MEMBERSHIP is called with group address and IPADDR_ANY) so it might be a bug in Python, too, although I'm not aware of any at the moment.

My host is ArchLinux, same behaviour can be observed with current ghcr.io/home-assistant/home-assistant:stable (at the time of writing 2021.10.6)
```
# uname -a
Linux redblade 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux
# python --version 
Python 3.9.7
```

Adding the following code ("172.16.238.3" is eth1 interface address)
```python
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton("224.0.1.187") + socket.inet_aton("172.16.238.3"))
```
below line 66 (refers to code below) solves the issue for me, although this hardly qualifies as workaround. A better solution would be to iterate over interface addresses as configured by the user in Home Assistant settings -> Server control -> General -> Networks sections.

https://github.com/home-assistant-libs/aioshelly/blob/b1deaa2484c1192946588b0b3e8db263f8fde999/aioshelly/coap.py#L59-L68

**Comment by buzz-tee** [comment]
You're right and that works fine, too. I will eventually switch to unicast, especially since Shelly is said to drop multicast entirely in favor of multicast (Facebook post by Dimitar Dimitrov, couldn't find the original source though...). But since I'm currently subscribing to my Shelly's from HA and OH3 while I'm comparing both solutions I cannot drop the multicast, yet.

So the intention behind starting the issue here was to trigger a discussion wether the feature should be fully supported as long as it exists or leave it as is and close with won't fix.

I could think of the following alternative solutions:

* let the Shelly's broadcast their CoAP messages - requires setting the network broadcast address as CoIoT peer in each device, but works just fine
* write a tiny unicast-multicaster that runs as a separate container and forwards unicast UDP to a pre-defined - requires the multicaster to be configured as CoIoT peer, too, but reduces the background noise on the network

**Comment by ingobecker** [comment]
As mentioned by @buzz-tee the code tries to use the network which has a default route setup. I'm running HA without an internet connection so there is no default route on any of the available networks. This causes the shelly integration to fail completely. I had to setup a default route on one of the available networks which doesn't do anything apart from preventing the shelly integration to throw an exception. It would be great if the shelly integration would just work in an environment without access to the internet and a default route.
From reading the logs it was also not obvious what caused the errors and how to fix it.

**Comment by chemelli74** [comment]
> From reading the logs it was also not obvious what caused the errors and how to fix it.

@buzz-tee I resume this old post because I realized now what you wrote here.
Do you mind sharing the logs and your hypothesis of fix ?

**Comment by ingobecker** [comment]
Sorry for the late reply, but your changes seem to fix the issue. I removed the bogus default route of my setup and everything seems to work as expected now. Thanks!
