### ISSUE TITLE
how to set a relay or output

### ISSUE THREAD

**Issue by rudyvan** [home-assistant-libs/aioshelly#170]
The example provided is clear on how to create a device and to subscribe to monitor updates.

But not so clear for me is how to use this module to set a relay, do i have to use the call script from RPCCall and provide json?

Alternatively i can use a http command to set outputs, and use aioshelly just for monitoring inputs and changes to outputs.
please advice

**Comment by thecode** [comment]
You need to use the `call_rpc` method:
https://github.com/home-assistant-libs/aioshelly/blob/404ac9631b47077e81737ae19320d3de6c7bafab/aioshelly/rpc_device.py#L145-L149

For complete documentation how to set a relay using this method read here:
https://shelly-api-docs.shelly.cloud/gen2/Components/FunctionalComponents/Switch#switchset
