### ISSUE TITLE
Shelly Plus 1PM  has no 'model' property

### ISSUE THREAD

**Issue by Crunchie** [home-assistant-libs/aioshelly#193]
Connecting to a Shelly Plus 1PM device via rpc, has no model returned

"model" property of the rpc_device throws an error when trying to access

```
pprint(device.model)
File "/home/sam/shelly/aioshelly/aioshelly/rpc_device.py", line 215, in model 
return cast(str, self.shelly["model"]) 
KeyError: 'model'
```

device info

```
pprint(device.shelly)

{'app': 'Plus1PM',
'auth_domain': None,
'auth_en': False,    
'fw_id': '20220218-155750/0.10.0-beta4-gb6aa07e',  
'gen': 2,                  
'id': 'shellyplus1pm- <XXXXXXX>  ',   
'mac': <XXXXXXX>    
'name':  <XXXXXXX>      
'ver': '0.10.0-beta4'}       
```
Same result running the current 0.9.3 and 0.9.0 firmwares

This error is also thrown when trying to configure the shelly device within Homeassistant

**Comment by Crunchie** [comment]
Ok - looking through documentation https://shelly-api-docs.shelly.cloud/gen2/Overview/CommonServices/Shelly#shellygetdeviceinfo model really should be returned

Using the http api I do not get model in the returned info either.

Im guessing this is a device bug, not this library

**Comment by chemelli74** [comment]
@Crunchie, thx fo reporting. I will open an internal ticket to Shelly.

Simone

**Comment by kzyapkov** [comment]
This is a pre-production sample device. It has not been provisioned, hence the missing model key.

**Comment by thecode** [comment]
> This is a pre-production sample device. It has not been provisioned, hence the missing model key.

I wonder how he got such unit, @kzyapkov what do you suggest? should he ask for replacement?

**Comment by kzyapkov** [comment]
Sorry, I left the above comment from my phone, and typing on a tiny touch keyboard is not my strong side.

Missing `model` key in a Shelly's device info means it doesn't have provisioning data. It was either tampered with -- flash was rewritten/erased, or it's a development/preproduction sample which didn't go through the provisioning and self-test procedures, or we botched the provisioning.

In any case, we cannot know if it's a genuine Gen2 Shelly. So, @Crunchie please open a ticket with Shelly support and tell us where you got that item from. It's possible we've sent out some non-provisioned samples to QA group members in the past, but we try to not do that anymore. As for what `aioshelly` can do about this ... well, log the error :)

**Comment by Crunchie** [comment]
Ha, ok thanks for that info, I will open a ticket.
FYI I had this issue on all three units I bought from the Shelly store on Ali-express
