### ISSUE TITLE
Integration needs reload after Shelly looses power

### ISSUE THREAD

**Issue by kjetilmjos** [home-assistant-libs/aioshelly#21]
Just had a power outage at home. I had to manually go to the home assistant integration and reload it for each Shelly. Did not have this issue before when using MQTT. Is this how it should work after a power outage?

**Comment by thecode** [comment]
I tried to reproduce this on my system without success:

- Disconnect power to Shelly Plug S
- Wait until it is unavailable
- Reconnect power
- Wait until it is available again

It took about 30 seconds until the device appeared as available again.

Can you ad more details for your problem? (Does the HA system also shuts down, How much time did you wait)
Can you try to reproduce the same way I did and update.

**Comment by kjetilmjos** [comment]
Looked some more into it. Home assistant core was running during the power outage. Because it's running on a laptop with battery. The issue seems to be unrelated to the power outage. I saw the same thing this morning. The Shelly integration needs to be reloaded to gain control of the lights again. Had a look in the logs:


```Logger: homeassistant.components.shelly
Source: components/shelly/__init__.py:88
Integration: Shelly (documentation, issues)
First occurred: September 24, 2020, 3:44:01 PM (4 occurrences)
Last logged: 1:01:10 AM

Unexpected error fetching shelly1-B8BB32 data: [Errno 113] Host is unreachable
Unexpected error fetching shelly1-B8BB45 data: [Errno 113] Host is unreachable
Unexpected error fetching shelly1-B8E1DE data: [Errno 113] Host is unreachable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 88, in _async_update_data
    return await self.device.update()
  File "/usr/local/lib/python3.8/site-packages/aioshelly/__init__.py", line 151, in update
    self._update_s(await self.coap_request("s"))
  File "/usr/local/lib/python3.8/site-packages/aioshelly/__init__.py", line 182, in coap_request
    response = await self.coap_context.request(request).response
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 731, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/usr/local/lib/python3.8/site-packages/aiocoap/protocol.py", line 783, in _run
    blockresponse = await blockrequest.response
OSError: [Errno 113] Host is unreachable

```

Could this be some timeout retry issue?

**Comment by bieniu** [comment]
`OSError` is already fixed https://github.com/home-assistant/core/pull/40393

**Comment by kjetilmjos** [comment]
Ahh thanks! Will close the issue and test more after 0.115.3 release.
