### ISSUE TITLE
Cannot check switch input states on shelly 2.5

### ISSUE THREAD

**Issue by cyberplant** [home-assistant-libs/aioshelly#22]
Hello!

I want to know the status of the physical switches that are attached to shelly 2.5. 

Let me explain it with my use case: I have a wall plate with 2 switches, but only 1 light attached in "output". The other one is a smart bulb that I turn on/off with an automation attached to the second switch.

This information is currently being reported in the example.py, so I guess it's just a matter of creating the correspondent binary_sensor on hass? (that's how shelly4hass does it).

Regards!

**Comment by bieniu** [comment]
I think we need listen multicast to implement input events. Now we poll devices every 5 sec.

**Comment by balloob** [comment]
@cyberplant this is the repository for a library to talk to Shelly products. For feature requests related to Home Assistant, use the appropriate forums https://community.home-assistant.io/c/feature-requests/13
