### ISSUE TITLE
Get light entities for switches on shelly 2.5 when LOAD TYPE = Lights.

### ISSUE THREAD

**Issue by cyberplant** [home-assistant-libs/aioshelly#23]
About this one, I don't know if it's possible.. I mean, if this data is being published somehow by COAP on Shelly.

If you can give me a bit more information about how to debug that, I can investigate, and if this data is really not there, we can talk with Shelly people, maybe they can add that to the next firmware.

**Comment by cyberplant** [comment]
I think this information is not being stored currently on the device, so that's why we cannot get it. I created a support ticket to check with them if it's possible to store it there.. let's see!

**Comment by bieniu** [comment]
Load type should be available via CoAP after the next Shelly firmware update.

**Comment by kzyapkov** [comment]
Yeah, we're calling it `appliance_type`

**Comment by bieniu** [comment]
@kzyapkov Will the `appliance_type` be configurable from the device's web panel or only from the Shelly app?

**Comment by kzyapkov** [comment]
It will be a setting, similar to `name`, per-channel, settable via app or HTTP. We will accept any string, but the app will only interpret a predefined set of values, anything else will be treated as "general".

**Comment by chemelli74** [comment]
Implementation in progress on HA integration side: [Shelly: handle light domain for relay switches ( fw >=1.9 )](https://github.com/home-assistant/core/pull/42508)

Closing the issue as is not a library issue.

Simone
