### ISSUE TITLE
BUG: Shelly Door/Window 2 is getting Unavailable in latest version

### ISSUE THREAD

**Issue by robinostlund** [home-assistant-libs/aioshelly#242]
Hi,
After upgrading to latest version of homeassistant (2022.07.7) i have started to get issues with my shelly door window 2 sensor. It is currently mounted in my garage to see the state of the door. The issue i see is that its sensors get unavailable and i see this is the logs:
```
2022-07-30 14:03:34 ERROR (MainThread) [homeassistant.components.shelly] Error fetching Garage door sensor data: Sleeping device did not update within 43200 seconds interval
```

So it starts to alert after 12 hours as it now seems to expect a 43200 interval and this often the door doesnt get opened. 
Is it something in the latest release that could have caused this? as i see the version of aioshelly has increased in version 2022.07.7?

Brg
Robin

**Comment by thecode** [comment]
This repository is related to issues with `aioshelly` and is mainly for developers use.
Issues for Home Assistant Shelly should be created here as there is a detailed template for that there: https://github.com/home-assistant/core/issues

Before creating a new issue please look at https://github.com/home-assistant/core/issues/56101 and https://github.com/home-assistant/core/issues/60123
If it does not help create an issue in the core repo.
Thanks
