### ISSUE TITLE
aioshelly BLE script MAC address filtering

### ISSUE THREAD

**Issue by RadekHvizdos** [home-assistant-libs/aioshelly#389]
Hi all,

While preparing the rollout of our product, we have noticed that enabling shelly BLE scanning (in order to support Shelly BLU), causes quite an increase in network traffic. As there will be many Shellies on the same network, the effect gets amplified.

The script "aioshelly BLE script 1.0" reports every single BLE scan result to Home Assistant, without any means of rate limiting or filtering. As we are only interested in supporting Shelly BLU, would it be possible to filter the scan results based on mac prefix and only report matching devices? For example the following is working quite well:

```
// aioshelly BLE script 1.0 - filtered
BLE.Scanner.Subscribe(function (ev, res) {
    if (ev === BLE.Scanner.SCAN_RESULT) {
      prefix = "5c:c7:c1";
      if (res.addr.slice(0, prefix.length) === prefix)
      {
          Shelly.emitEvent("ble.scan_result", [
              1,
              res.addr,
              res.rssi,
              btoa(res.advData),
              btoa(res.scanRsp)
          ]);
      }
    }
});
BLE.Scanner.Start({
    duration_ms: -1,
    active: false,
    interval_ms: 320,
    window_ms: 30,
}); 
```
Ideally the prefix list would be dynamic/adjustable, so that others could use this to target devices from a different vendor.

Thanks!

**Comment by thecode** [comment]
You can manually upload any script you want to the device and do not enable the BT proxy from HA. 
We can't support different scripts as there are endless options with scripts (I am already using a different script for another purpose)

**Comment by RadekHvizdos** [comment]
Hi @thecode,

OK, that could work for us. But when we disable the BT proxy in HA, the BT scanner gets unregistered and we don't receive any data from BLU devices:

> DEBUG (MainThread) [homeassistant.components.bluetooth.manager] Unregistering scanner shelly_ble (48:55:19:05:21:24)

We can still see the BLE scan events in our MQTT Debug connection, they are just not being processed in HA anymore.

Is there a way how this could be achieved?

Thank you for your support.

**Comment by RadekHvizdos** [comment]
> You can manually upload any script you want to the device and do not enable the BT proxy from HA. We can't support different scripts as there are endless options with scripts (I am already using a different script for another purpose)

Is there a way how we could use a custom BLE scanning script with stock Home Assistant BT Proxy implementation? As mentioned earlier disabling BT proxy in HA stops  the processing of data from BLU devices...

**Comment by bieniu** [comment]
Do I understand correctly, you want to use the HA BT proxy but not use its script, which is an integral part of the HA BT proxy? Users use BT proxy for devices from different manufacturers, so MAC filtering is not a good idea.

**Comment by g-kiss** [comment]
@thecode : Would it be possible to have a fourth option "Own script" at this point?

![kép](https://github.com/home-assistant-libs/aioshelly/assets/70820303/5cb57d0b-781c-4ef8-a91d-41eb73748483)

**Comment by chemelli74** [comment]
Hi @RadekHvizdos, thank you for suggestion.

We internally evaluated pros and contras and decided not going with your suggestion.
The risk that unskilled users change the script and complain is not working are too high for us.

In any way, I want to propose you a couple of steps that may resolve your issue:

- enable Bluetooth scanner mode from HA
- connect to the device via its own Web UI and overwrite the script with your own

That way you should achive your goal.

Let me know if it works for you.

**Comment by g-kiss** [comment]
@chemelli74 As I know that Shelly integration overwrites the script every time, when device is connecting or when HA restarts.

**Comment by RayOfLight1** [comment]
Not only it overwrites it constantly, but if I select "Disabled" in the Hass Bluetooth scanner mode and then I run the shelly plus script manually, without the remote upload, it still does not work, as it seems that the shelly script callbacks are not listened by my hass install. So I'm a bit lost.

**Comment by bieniu** [comment]
After internal discussion it was decided that such a change was not necessary.
