### ISSUE TITLE
Script memory overflow while using Shelly Gen2+ devices as Bluetooth proxy

### ISSUE THREAD

**Issue by taulfsime** [home-assistant-libs/aioshelly#477]
The existing script, responsible for directing Bluetooth packets from the Shelly device scanner to HA, may lead to memory overflow. This results in script crashes and the corresponding feature becoming nonfunctional.

The issue is coming from the fact that all Bluetooth packets are forwarded and the script uses an anonymous function to emit the event. 
Also, limiting the requests will help the flawless work of the script/feature.

Collaborating with the user, we confirmed that the revised script (V2) maintains the functionality of the previous version while addressing the issue of the script crashes after some time.

**Comment by chemelli74** [comment]
Should be fixed by #478
