### ISSUE TITLE
Matching of UL model numbers

### ISSUE THREAD

**Issue by tomcastleman** [home-assistant-libs/aioshelly#700]
Hi there, I just bought a Shelly Pro 2 v.1 and (despite purchasing it in EU) it's a UL model with the model number:

`SPSW-202XE12UL` rather than
`SPSW-202XE16EU`

I notice that this library doesn't appear to handle the UL model numbers which I assume is why in Home Assistant the model name is missing / Unknown.

- Is this a known limitation of the library?

- Aside from the cosmetic missing model name, would the lack of matching UL models have any other negative affect on the operation of the UL models in Home Assistant? (I haven't noticed any yet).

- Would you be open to a PR to add a feature to match UL models?

Thanks

**Comment by chemelli74** [comment]
Hi @tomcastleman ,
as you already supposed, is only esthetical. 
No functionalities are impacted by the missing model name.

You are more than welcome in creating a PR to add those models.

**Comment by thecode** [comment]
Fixed by #701
