### ISSUE TITLE
Logger: aioshelly.coap

### ISSUE THREAD

**Issue by FCKotze** [home-assistant-libs/aioshelly#72]
Logger: aioshelly.coap
Source: /usr/local/lib/python3.8/site-packages/aioshelly/coap.py:29
First occurred: 11:47:03 AM (1 occurrences)
Last logged: 11:47:03 AM

CoAP message of type 69 from host 192.168.86.234 is not a valid JSON format: b"XE'\x1e\t\x0c\xdf=q\x11\xe1\xc2\xb3oic\x02ad\x11<\xe1\xfe\xdb\xc0\xff\xbfcnon\x1a\x94\xa2L\xe6cttl\x18<ctrg\xe0brtioic.wk.ad\xff"

I have this error pop up in my Home Assistant Logs a few times a day, when I check which device it related to based on the IP Address listed its my Samsung Robot Vacuum. I decided to double check to make sure its the vacuum causing this error by assigning it a different IP address and yes the new IP address i assigned then gets listed on the error. I have no idea why my Samsung Robot Vacuum would give a Shelly Integration Error. Nothing stops working and no entities become unavailable, yet this error message would appear several times a day. Hope you would be able to shed some light on this issue for m. Thanks

**Comment by thecode** [comment]
Thanks @FCKotze, I will issue a fix to filter only Shelly IPs in the next days

**Comment by FCKotze** [comment]
Thanks @thecode , much appreciated!

**Comment by balloob** [comment]
But then we can't detect new Shelly devices anymore with our coap listener. Maybe only print as warning if the IP is not known to be Shelly?

**Comment by thecode** [comment]
Currently we do not use CoAP to detect new devices, but indeed we had a plan for it.
What we do now is we parse the message here:
https://github.com/home-assistant-libs/aioshelly/blob/1d25c9030870b4640ddace243664adfcd82013ee/aioshelly/coap.py#L88
And if the IP is not in the list we drop the message here:
https://github.com/home-assistant-libs/aioshelly/blob/1d25c9030870b4640ddace243664adfcd82013ee/aioshelly/coap.py#L97

The reason I did not submit a fix yet is that is that indeed it will remove the option to detect devices using CoAP. 
The problem with using port 5683 is that it is a standard CoAP port, and although now in home usage we only see it with Shelly, it maybe be used by other devices in the future.

**Comment by balloob** [comment]
I think in that case, we should not log it as a warning but debug and silently discard the message.

**Comment by chemelli74** [comment]
> I think in that case, we should not log it as a warning but debug and silently discard the message.

We already do: https://github.com/home-assistant-libs/aioshelly/blob/1d25c9030870b4640ddace243664adfcd82013ee/aioshelly/coap.py#L37

Simone

**Comment by chemelli74** [comment]
> I think in that case, we should not log it as a warning but debug and silently discard the message.

We need the warning if the packet is from Shelly as this indicate that the packet is corrupted ( network or firmware related ).

**Comment by thecode** [comment]
@chemelli74 I think we can log this as debug, if there is a user experience a problem we ask him to send debug logs anyhow.

**Comment by chemelli74** [comment]
> @chemelli74 I think we can log this as debug, if there is a user experience a problem we ask him to send debug logs anyhow.

This is indeed an option.
