### ISSUE TITLE
Colot/coap unicast support

### ISSUE THREAD

**Issue by mamrai1** [home-assistant-libs/aioshelly#82]
I have changed some of my shellies to use unicast peer instead of multicast and used 'home assistant' ip with 5683 port.. It seems that is working fine. At the beginning is used ha ip with 8123 port but any state changes on Shelly devices where not shown(if triggered outside of HA)

**Comment by bieniu** [comment]
`aioshelly` supports multicast and unicast.

**Comment by mamrai1** [comment]
Someone should update Shelly integration documentation so users know which port is used for unicsst

**Comment by Misiu** [comment]
@mamrai1 [this](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/shelly.markdown) is the source of Shelly integration description (https://www.home-assistant.io/integrations/shelly/). You can click Edit and suggest a change. Help is more than welcome 🙂

**Comment by thecode** [comment]
It is already there for next version:
https://github.com/home-assistant/home-assistant.io/pull/17083#event-4490158288

You can preview it here:
https://deploy-preview-17083--home-assistant-docs.netlify.app/integrations/shelly/

@mamrai1 I am closing this issue, if there is a need for a docs change please open one on the docs repository as suggested by @Misiu
